version: "3.3"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nardi@project.com
      PGADMIN_DEFAULT_PASSWORD: password

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admintest
      POSTGRES_DB: ecoleabc
      POSTGRES_USER: nardi
    ports:
      - "54366:5432"
  server:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:3000"
